# Generated by Django 2.2.5 on 2019-09-14 18:46

import climbing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingLocation',
            fields=[
                ('ClimbingLocationId', models.AutoField(primary_key=True, serialize=False)),
                ('Coordinates', models.CharField(max_length=250, unique=True)),
                ('Province', models.CharField(choices=[('HE', 'Heredia'), ('AL', 'Alajuela'), ('SJ', 'San Jose'), ('CA', 'Cartago'), ('GU', 'Guanacaste'), ('LI', 'Limon')], default='SJ', max_length=100)),
                ('Name', models.CharField(max_length=250, unique=True)),
                ('DescriptionMarkDown', models.TextField()),
                ('DescriptionMarkHTML', models.TextField()),
                ('Address', models.CharField(max_length=500)),
            ],
            bases=(models.Model, climbing_app.models.Province),
        ),
    ]
