# Generated by Django 2.2.5 on 2019-09-14 19:11

import climbing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingGym',
            fields=[
                ('ClimbingGymId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Province', models.CharField(choices=[('HE', 'Heredia'), ('AL', 'Alajuela'), ('SJ', 'San Jose'), ('CA', 'Cartago'), ('GU', 'Guanacaste'), ('LI', 'Limon')], default='SJ', max_length=100)),
                ('Address', models.CharField(max_length=500)),
            ],
            bases=(models.Model, climbing_app.models.Province),
        ),
    ]
