# Generated by Django 2.2.5 on 2019-09-17 01:20

import climbing_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0002_climbinggym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('boulder_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LocationArea',
            fields=[
                ('location_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description_markdown', models.TextField()),
                ('description_HTML', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SportRoute',
            fields=[
                ('sport_route_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('yds_grade', models.CharField(choices=[(0, '5.4'), (1, '5.5'), (2, '5.6'), (3, '5.7'), (4, '5.8'), (5, '5.9'), (6, '5.10a'), (7, '5.10b'), (8, '5.10C'), (9, '5.10d'), (10, '5.11a'), (11, '5.11b'), (12, '5.11C')], max_length=10)),
                ('font_grade', models.CharField(choices=[(0, '4A'), (1, '4A+'), (2, '4B'), (3, '4B+'), (4, '4C'), (5, '4C+'), (6, '5A'), (7, '5A+'), (8, '5B'), (9, '5B+'), (10, '5C'), (11, '5C+'), (12, '6A'), (13, '6A+'), (14, '6B'), (15, '6B+'), (16, '6C'), (17, '6C+'), (18, '7A'), (19, '7A+'), (20, '7B'), (21, '7B+'), (22, '7C'), (23, '7C+'), (24, '8A'), (25, '8A+'), (26, '8B'), (27, '8B+'), (28, '8C'), (29, '8C+'), (30, '9A'), (31, '9A+'), (32, '9B'), (33, '9B+'), (34, '9C'), (35, '9C+')], max_length=10)),
                ('is_project', models.BooleanField()),
                ('location_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing_app.LocationArea')),
            ],
            bases=(models.Model, climbing_app.models.YDSGrade, climbing_app.models.FontGrade),
        ),
        migrations.RenameField(
            model_name='climbinggym',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='climbinggym',
            old_name='ClimbingGymId',
            new_name='climbing_gym_id',
        ),
        migrations.RenameField(
            model_name='climbinggym',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='climbinggym',
            old_name='Province',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='climbinglocation',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='climbinglocation',
            old_name='ClimbingLocationId',
            new_name='climbing_location_id',
        ),
        migrations.RenameField(
            model_name='climbinglocation',
            old_name='Coordinates',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='climbinglocation',
            old_name='DescriptionMarkHTML',
            new_name='description_HTML',
        ),
        migrations.RenameField(
            model_name='climbinglocation',
            old_name='DescriptionMarkDown',
            new_name='description_markdown',
        ),
        migrations.RenameField(
            model_name='climbinglocation',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='climbinglocation',
            old_name='Province',
            new_name='province',
        ),
        migrations.AddField(
            model_name='climbinggym',
            name='coordinates',
            field=models.CharField(default='0,0', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SportRouteImage',
            fields=[
                ('sport_route_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('imageUrl', models.URLField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing_app.SportRoute')),
            ],
        ),
        migrations.AddField(
            model_name='locationarea',
            name='climbing_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing_app.ClimbingLocation'),
        ),
        migrations.CreateModel(
            name='BoulderRoute',
            fields=[
                ('boulder_route_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_grade', models.CharField(choices=[(0, 'V0'), (1, 'V1'), (2, 'V2'), (3, 'V3'), (4, 'V4'), (5, 'V5'), (6, 'V6'), (7, 'V7'), (8, 'V8'), (9, 'V9'), (10, 'V10'), (11, 'V11'), (12, 'V12'), (13, 'V13'), (14, 'V14'), (15, 'V15'), (16, 'V16')], max_length=10)),
                ('is_project', models.BooleanField()),
                ('is_high_ball', models.BooleanField()),
                ('is_sit_start', models.BooleanField()),
                ('description', models.CharField(max_length=500)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing_app.Boulder')),
            ],
            bases=(models.Model, climbing_app.models.VGrade),
        ),
        migrations.CreateModel(
            name='BoulderImage',
            fields=[
                ('route_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing_app.Boulder')),
            ],
        ),
        migrations.AddField(
            model_name='boulder',
            name='location_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing_app.LocationArea'),
        ),
    ]
