# Generated by Django 2.2.5 on 2019-09-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0003_auto_20190916_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbinggym',
            name='coordinates',
            field=models.CharField(default='0,0', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='climbinglocation',
            name='coordinates',
            field=models.CharField(default='0,0', max_length=250, unique=True),
        ),
    ]
