# Generated by Django 2.2.5 on 2019-09-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0004_auto_20190916_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportroute',
            name='yds_grade',
            field=models.CharField(choices=[(0, '5.4'), (1, '5.5'), (2, '5.6'), (3, '5.7'), (4, '5.8'), (5, '5.9'), (6, '5.10a'), (7, '5.10b'), (8, '5.10c'), (9, '5.10d'), (10, '5.11a'), (11, '5.11b'), (12, '5.11c'), (13, '5.11d'), (14, '5.12a'), (15, '5.12b'), (16, '5.12c'), (17, '5.12d'), (18, '5.13a'), (19, '5.13b'), (20, '5.13c'), (21, '5.13d'), (22, '5.14a'), (23, '5.14b'), (24, '5.14c'), (25, '5.14d'), (26, '5.15a'), (27, '5.15b'), (28, '5.15c'), (29, '5.15d')], max_length=10),
        ),
    ]
