# Generated by Django 2.2.5 on 2019-09-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0005_auto_20190916_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulderroute',
            name='v_grade',
            field=models.CharField(choices=[('V0', 'V0'), ('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3'), ('V4', 'V4'), ('V5', 'V5'), ('V6', 'V6'), ('V7', 'V7'), ('V8', 'V8'), ('V9', 'V9'), ('V10', 'V10'), ('V11', 'V11'), ('V12', 'V12'), ('V13', 'V13'), ('V14', 'V14'), ('V15', 'V15'), ('V16', 'V16')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sportroute',
            name='font_grade',
            field=models.CharField(choices=[('4A', '4A'), ('4A+', '4A+'), ('4B', '4B'), ('4B+', '4B+'), ('4C', '4C'), ('4C+', '4C+'), ('5A', '5A'), ('5A+', '5A+'), ('5B', '5B'), ('5B+', '5B+'), ('5C', '5C'), ('5C+', '5C+'), ('6A', '6A'), ('6A+', '6A+'), ('6B', '6B'), ('6B+', '6B+'), ('6C', '6C'), ('6C+', '6C+'), ('7A', '7A'), ('7A+', '7A+'), ('7B', '7B'), ('7B+', '7B+'), ('7C', '7C'), ('7C+', '7C+'), ('8A', '8A'), ('8A+', '8A+'), ('8B', '8B'), ('8B+', '8B+'), ('8C', '8C'), ('8C+', '8C+'), ('9A', '9A'), ('9A+', '9A+'), ('9B', '9B'), ('9B+', '9B+'), ('9C', '9C'), ('9C+', '9C+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sportroute',
            name='yds_grade',
            field=models.CharField(choices=[('5.4', '5.4'), ('5.5', '5.5'), ('5.6', '5.6'), ('5.7', '5.7'), ('5.8', '5.8'), ('5.9', '5.9'), ('5.10a', '5.10a'), ('5.10b', '5.10b'), ('5.10c', '5.10c'), ('5.10d', '5.10d'), ('5.11a', '5.11a'), ('5.11b', '5.11b'), ('5.11c', '5.11c'), ('5.11d', '5.11d'), ('5.12a', '5.12a'), ('5.12b', '5.12b'), ('5.12c', '5.12c'), ('5.12d', '5.12d'), ('5.13a', '5.13a'), ('5.13b', '5.13b'), ('5.13c', '5.13c'), ('5.13d', '5.13d'), ('5.14a', '5.14a'), ('5.14b', '5.14b'), ('5.14c', '5.14c'), ('5.14d', '5.14d'), ('5.15a', '5.15a'), ('5.15b', '5.15b'), ('5.15c', '5.15c'), ('5.15d', '5.15d')], max_length=10),
        ),
    ]
