# Generated by Django 2.2.5 on 2019-09-17 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0006_auto_20190916_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportroute',
            name='distance',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='sportroute',
            name='quick_draw_qty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
