# Generated by Django 2.2.5 on 2019-09-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0007_auto_20190916_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationarea',
            name='climbing_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='climbing_app.ClimbingLocation'),
        ),
        migrations.AlterField(
            model_name='sportroute',
            name='location_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_routes', to='climbing_app.LocationArea'),
        ),
    ]
