# Generated by Django 2.2.5 on 2019-09-28 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0008_auto_20190916_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulderimage',
            name='boulder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boulder_images', to='climbing_app.Boulder'),
        ),
        migrations.AlterField(
            model_name='sportrouteimage',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_images', to='climbing_app.SportRoute'),
        ),
    ]
